Make jest a dev dependency
P-Copley/jest-sorted pull request #2
Opened 2020-06-05 13:53 UTC by jwaimann

2020-06-06 16:41 UTC, P-Copley requested changes

2020-06-06 16:41 UTC, P-Copley commented on package.json
> +  "dev-dependencies": {
```suggestion
  "devDependencies": {
```

Good point, it should be a dev dependency. Should be camelCased but happy to accept otherwise :D

2020-06-08 10:29 UTC, jwaimann commented
thanks @P-Copley , change applied

2020-06-09 08:10 UTC, P-Copley approved these changes

2020-06-09 08:10 UTC, merged